apiVersion: v1
kind: Namespace
metadata:
  name: minecraft-server
  labels:
    app: minecraft-server
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-server-data
  namespace: minecraft-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: hcloud-volumes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server
  namespace: minecraft-server
  labels:
    app: minecraft-server
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: minecraft-server
  template:
    metadata:
      labels:
        app: minecraft-server
    spec:
      initContainers:
        - name: accept-eula
          image: busybox
          command:
            - /bin/sh
            - -c
            - >
              echo 'eula=true' > /data/eula.txt
          volumeMounts:
            - mountPath: "/data"
              name: minecraft-server-volume
      containers:
        - name: minecraft-server
          image: ghcr.io/dotkuro/minecraft-server:latest
          imagePullPolicy: Always
          ports:
            - name: minecraft-tcp
              containerPort: 25565
              protocol: TCP
            - name: minecraft-rcon
              containerPort: 25575
              protocol: TCP
          env:
            - name: MIN_MEMORY_G
              value: "1"
            - name: MAX_MEMORY_G
              value: "6"
          volumeMounts:
            - mountPath: "/server/data"
              name: minecraft-server-volume
          resources:
            requests:
              memory: 2Gi
              cpu: 500m
            limits:
              memory: 7Gi
              cpu: 1000m
      volumes:
        - name: minecraft-server-volume
          persistentVolumeClaim:
            claimName: minecraft-server-data
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-server
  namespace: minecraft-server
  labels:
    app: minecraft-server
  annotations:
    load-balancer.hetzner.cloud/name: lb2.cluster1
    load-balancer.hetzner.cloud/location: fsn1
    load-balancer.hetzner.cloud/uses-proxyprotocol: "false"
    load-balancer.hetzner.cloud/hostname: lb2.cluster1.dotku.ro
spec:
  type: LoadBalancer
  ports:
    - name: minecraft-tcp
      port: 25565
      targetPort: minecraft-tcp
  selector:
    app: minecraft-server
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-rcon
  namespace: minecraft-server
  labels:
    app: minecraft-server
spec:
  ports:
    - name: minecraft-rcon
      port: 25575
      targetPort: minecraft-rcon
  selector:
    app: minecraft-server