apiVersion: v1
kind: Namespace
metadata:
  name: minecraft-server
  labels:
    app: minecraft-server
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-server-data
  namespace: minecraft-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: hcloud-volumes